project(
    "sah_kd_tree"
    LANGUAGES
        CUDA)

skt_add_library(
    "${PROJECT_NAME}"
    SOURCES
        "${PROJECT_NAME}_export.h"
        "${PROJECT_NAME}.cuh"
        "${PROJECT_NAME}_inline.cuh"
        "builder.cu"
        "builder.inl"
        "calculate_root_node_bbox.cu"
        "calculate_root_node_bbox.inl"
        "calculate_rope.cu"
        "calculate_rope.inl"
        "calculate_triangle_bbox.cu"
        "calculate_triangle_bbox.inl"
        "check_tree.inl"
        "check_tree.cu"
        "decouple_event_both.inl"
        "decouple_event_both.cu"
        "determine_polygon_side.inl"
        "determine_polygon_side.cu"
        "filter_layer_node_offset.inl"
        "filter_layer_node_offset.cu"
        "find_perfect_split.inl"
        "find_perfect_split.cu"
        "generate_initial_event.inl"
        "generate_initial_event.cu"
        "link_triangle.inl"
        "link_triangle.cu"
        "merge_event.inl"
        "merge_event.cu"
        "populate_leaf_node_triangle_range.inl"
        "populate_leaf_node_triangle_range.cu"
        "populate_node_parent.inl"
        "populate_node_parent.cu"
        "resize_node.inl"
        "resize_node.cu"
        "select_node_best_split.inl"
        "select_node_best_split.cu"
        "separate_splitted_polygon.inl"
        "separate_splitted_polygon.cu"
        "set_node_count.inl"
        "set_node_count.cu"
        "split_node.inl"
        "split_node.cu"
        "split_polygon.inl"
        "split_polygon.cu"
        "update_polygon_node.inl"
        "update_polygon_node.cu"
        "update_splitted_polygon_count.inl"
        "update_splitted_polygon_count.cu"
        "update_splitted_polygon_node.inl"
        "update_splitted_polygon_node.cu"
    PUBLIC_LINKS
        Thrust
        fmt::fmt)

if(${SAH_KD_TREE_BUILD_FUZZER})
    target_compile_options(
        "lib${PROJECT_NAME}"
        PRIVATE
            $<$<COMPILE_LANGUAGE:CXX>:$<$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>>:-fsanitize=fuzzer-no-link>>)
    target_link_options(
        "lib${PROJECT_NAME}"
        PRIVATE
            $<$<COMPILE_LANGUAGE:CXX>:$<$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>>:-fsanitize=fuzzer-no-link>>)
    string(REPLACE "." ";" CXX_COMPILER_VERSION_LIST ${CMAKE_CXX_COMPILER_VERSION})
    list(GET CXX_COMPILER_VERSION_LIST 0 CXX_COMPILER_VERSION_MAJOR)
    target_link_directories(
        "lib${PROJECT_NAME}"
        PUBLIC
            "/usr/lib/clang/${CXX_COMPILER_VERSION_MAJOR}/lib/linux/")
    target_link_libraries(
        "lib${PROJECT_NAME}"
        PUBLIC
            "clang_rt.fuzzer_no_main-${CMAKE_SYSTEM_PROCESSOR}")  # not needed for 'fuzzer' target, but works fine
endif()
