project("engine")

skt_add_library(
    SOURCES
        "${PROJECT_NAME}_export.h"
        "context.hpp"
        "context.cpp"
        "fwd.hpp"
        "device_features.hpp"
        "buffer.hpp"
        "image.hpp"
        "vma.hpp"
        "vma.cpp"
        "exception.hpp"
        "exception.cpp"
        "debug_utils.hpp"
        "debug_utils.cpp"
        "utils.hpp"
        "utils.cpp"
        "types.hpp"
        "types.cpp"
        "file_io.hpp"
        "file_io.cpp"
        "memory.hpp"
        "memory.cpp"
        "library.hpp"
        "library.cpp"
        "instance.hpp"
        "instance.cpp"
        "physical_device.hpp"
        "physical_device.cpp"
        "fence.hpp"
        "fence.cpp"
        "device.hpp"
        "device.cpp"
        "command_buffer.hpp"
        "command_buffer.cpp"
        "command_pool.hpp"
        "command_pool.cpp"
        "queue.hpp"
        "queue.cpp"
        "shader_module.hpp"
        "shader_module.cpp"
        "render_pass.hpp"
        "render_pass.cpp"
        "pipeline_cache.hpp"
        "pipeline_cache.cpp"
        "pipeline_layout.hpp"
        "pipeline_layout.cpp"
        "specialization_info.hpp"
        "specialization_info.cpp"
        "compute_pipeline.hpp"
        "compute_pipeline.cpp"
        "graphics_pipeline.hpp"
        "graphics_pipeline.cpp"
        "spirv_reflect_dump.hpp"
        "spirv_reflect_dump.cpp"
        "descriptors.hpp"
        "descriptors.cpp"
        "push_constant_ranges.hpp"
        "push_constant_ranges.cpp"
        "render_graph.hpp"
        "render_graph.cpp"
    PRIVATE_LINKS
        "libcommon"
        "gli"
        "VulkanMemoryAllocator"
        "SPIRV-Reflect"
        "libformat"
        "libcodegen_spirv_format"
        "libcodegen_vulkan_utils"
        "nlohmann_json"
    PUBLIC_LINKS
        Vulkan::Headers
)

set_source_files_properties(
    "library.cpp"
    PROPERTIES
        VULKAN_HPP_STORAGE_SHARED_EXPORT 1
)

skt_add_executable()

add_subdirectory("tests")

if(${ipo_is_supported})
    set_target_properties(
        "lib${PROJECT_NAME}"
        "${PROJECT_NAME}"
        PROPERTIES
            INTERPROCEDURAL_OPTIMIZATION TRUE
    )
endif()
