project("utils")

skt_add_library(
    SOURCES
        "${PROJECT_NAME}_export.h"
        "${PROJECT_NAME}.hpp"
        "${PROJECT_NAME}.cpp"
        "assert.cpp"
        "assert.hpp"
        "auto_cast.cpp"
        "auto_cast.hpp"
        "checked_ptr.cpp"
        "checked_ptr.hpp"
        "demangle.cpp"
        "demangle.hpp"
        "exception.cpp"
        "exception.hpp"
        "fast_pimpl.cpp"
        "fast_pimpl.hpp"
        "fd.cpp"
        "fd.hpp"
        "get_if.cpp"
        "get_if.hpp"
        "hash.cpp"
        "hash.hpp"
        "math.cpp"
        "math.hpp"
        "mem_array.cpp"
        "mem_array.hpp"
        "meta.cpp"
        "meta.hpp"
        "noncopyable.cpp"
        "noncopyable.hpp"
        "overloaded.cpp"
        "overloaded.hpp"
        "pp.hpp"
        "random.cpp"
        "random.hpp"
        "scope_guard.cpp"
        "scope_guard.hpp"
        "scope_timer.cpp"
        "scope_timer.hpp"
)

add_subdirectory("tests")

