#pragma once

#define STRINGIZE2(x) #x
#define STRINGIZE(x) STRINGIZE2(x)

#define SOURCE_LOCATION __FILE__ "(" STRINGIZE(__LINE__) ")"

// FOR_EACH from https://www.scs.stanford.edu/~dm/blog/va-opt.html
#define SKT_PARENS ()
#define SKT_EXPAND(...) SKT_EXPAND4(SKT_EXPAND4(SKT_EXPAND4(SKT_EXPAND4(__VA_ARGS__))))
#define SKT_EXPAND4(...) SKT_EXPAND3(SKT_EXPAND3(SKT_EXPAND3(SKT_EXPAND3(__VA_ARGS__))))
#define SKT_EXPAND3(...) SKT_EXPAND2(SKT_EXPAND2(SKT_EXPAND2(SKT_EXPAND2(__VA_ARGS__))))
#define SKT_EXPAND2(...) SKT_EXPAND1(SKT_EXPAND1(SKT_EXPAND1(SKT_EXPAND1(__VA_ARGS__))))
#define SKT_EXPAND1(...) __VA_ARGS__
#define SKT_FOR_EACH(macro, ...) __VA_OPT__(SKT_EXPAND(SKT_FOR_EACH_HELPER(macro, __VA_ARGS__)))
#define SKT_FOR_EACH_HELPER(macro, a1, ...) macro(a1) __VA_OPT__(SKT_FOR_EACH_AGAIN SKT_PARENS(macro, __VA_ARGS__))
#define SKT_FOR_EACH_AGAIN() SKT_FOR_EACH_HELPER
